### ISSUE TITLE
Mapping issues to observing fields

### ISSUE THREAD

**Issue by eacmills** [ACES-CMZ/reduction_ACES#326]
Proposal ID | Obs ID | alternative name | velocity offset | 12m MOUS ID | issue | 7m MOUS ID | issue | TP MOUS ID | issue | TP MOUS ID2 | issue
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
cmz01 | a | - | 40 | X1590_X30aa | #242 | X1590_X30ac | #214 | X1590_X30ae | #215 |
cmz02 | b | Sgr B2 | 40 | X15a0_Xa6 | #150 | X15b4_X37 | #162 | X15a0_Xaa | #252 | -
cmz03 | c | - | 0 | X15a0_Xac | #256 | X15a0_Xae | #14 | X15a0_Xb0 | #175 | -
cmz04 | d | - | 30 | X15a0_Xb2 | #247 | X15a0_Xb4 | #228 | X15a0_Xb6 | #227 | -
cmz05 | e | - | -30 | X15a0_Xb8 | #147 | X15b4_X39 | #168 | X15a0_Xbc | #285 |-
cmz06 | f | - | 0 | - | - | - | -
cmz07 | g | - | 30 | X15a0_Xc4 | #134 | X15a0_Xc6 | #161 | X15a0_Xc8 | #197 |-
cmz08 | h | - | 0 | X15a0_Xca | #142 | X15a0_Xcc | #151 | X15a0_Xce | #177 |-
cmz09 | i | - | 30 | X15a0_Xd0 | #138 | X15b4_Xc5 | #191 | X15a0_Xd4 | #187 |-
cmz10 | j | - | 30 | X15b4_X3d | #117 | X15a0_Xd8 | #181 | X15a0_Xda | #32 | -
cmz11 | k | - | 30 | X15a0_Xdc | #152 | X15a0_Xde | #182 | X15a0_Xe0 | #193 | -
cmz12 | l | - | 0 | X15a0_Xe2 | #137 | X15a0_Xe4 | #153 | X15a0_Xe6 | #224 | -
cmz13 | m | - | 30 | X15b4_X41 | #118 | X15b4_X43 | #110 | X15b4_X45 | #170 | X15a0_Xec | #36
cmz14 | n | - | 30 | X15a0_Xee | #231 | X15a0_Xf0 | #225 | X15a0_Xf2 | #226 | -
cmz15 | o | - | 0 | - | | X15a0_Xf6 | #257 | X15a0_Xf8 | #278 | -
cmz16 | p | - | 0 | X15a0_Xfa | #149 | X15a0_Xfc | #148 | X15a0_Xfe | #183 | -
cmz17 | q | - | 0 | X15a0_X100 | #109 | X15a0_X102 | #171 | X15a0_X104 | #284 |-
cmz18 | r | - | 30 | X15a0_X106 | #263 | X15a0_X108 | #240 | X15a0_X10a | #246 | -
cmz19 | s | - | 0 | X15a0_X10c | #264 | X15a0_X10e | #243 | X15a0_X110 | #262 | -
cmz20 | t | - | 0 | X15a0_X112 | #113 | X15a0_X114 | #8 | X15a0_X116 | #172 | -
cmz21 | u | - | 30 | X15a0_X118 | #241 | X15a0_X11a | #216 | X15a0_X11c | #217 | -
cmz22 | v | - | 30 | X15a0_X11e | #235 | X15a0_X120 | #218 | X15a0_X122 | #219 | -
cmz23 | w | - | 30 | X15a0_X124 | #124 | X15a0_X126 | #144 | X15a0_X128 | #173 | -
cmz24 | x | - | 0 | X15a0_X12a | #125 | X15a0_X12c | #135 | X15a0_X12e | #164 | -
cmz25 | y | - | 0 | X15a0_X130 | #40 | X15a0_X132 | #4 |X15a0_X134 | #27 | -
cmz26 | z | - | 40 | X15a0_X136 | #131 | X15a9_X12d3 | #115 | X15a0_X13a | #236 | -
cmz27 | aa | - | 0 | X15a0_X13c | #251 | X15a0_X13e | #237 | X15a0_X140 | #229 | -
cmz28 | ab | - | 0 | X15a0_X142 | #129 | X15a0_X144 | #141 | X15a0_X146 | #167 | -
cmz29 | ac | - | 0 | X15a0_X148 | #232 | X15a0_X14a | #220 | X15a0_X14c | #221 | -
cmz30 | ad | - | 0 | X15a0_X14e | #28 | X15a0_X150 | #5 | X15a0_X152 | #25 |-
cmz31 | ae | - | 0 | X15a0_X154 | #132 | X15a0_X156 | #186 | X15a0_X158 | #180 | -
cmz32 | af | - | 0 | - | | X15a0_X15c | #244 | X15a0_X15e | #271 | -
cmz33 | ag | - | 0 | X15a0_X160 | #136 | X15a0_X162 | #174 | X15a0_X164 | #190 | -
cmz34 | ah | - | 30 | X15a0_X166 | #238 | X15a0_X168 | #230 | X15a0_X16a | #233 | -
cmz35 | ai | - | 0 | X15a0_X16c | #130 | X15a0_X16e | #143 | X15a0_X170 | #169 | -
cmz36 | aj | - | -30 | X15a0_X172 | #123 | X15b4_X47 | #119 | X15b4_X49 | #239 | X15a0_X176 | #26
cmz37 | ak | - | 30 | X15b4_X4b | #120 | X15a9_X12d5 | #116 | X15b4_X4d | #121 | X15a0_X17c | #13
cmz38 | al | - | 0 | - | | X15a0_X180 | #139 | X15a0_X182 | #166 | -
cmz39 | am | - | 30 | - | | - | | X15a0_X188 | #245 | -
cmz40 | an | - | 30 | X15a0_X18a | #133 | X15a0_X18c | #222 | X15a0_X18e | #184 | -
cmz41 | ao | Brick | 0 | X15a0_X190 | #41 | X15a0_X192 | #6 | X15a0_X194 | #29 | -
cmz42 | ap | - | 0 | X15a0_X196 | #43 | X15a0_X198 | #158 | X15a0_X19a | #30 | -
cmz43 | aq | Sgr A* | 0 | X15a0_X19c | #140 | X15a0_X19e | #33 | X15a0_X1a0 | #223 | -
cmz44 | ar | - | 40 | X15a0_X1a2 | #114 | X15b4_X4f | #159 | - | | -
cmz45 | as | - | 0 | X15a0_X1a8 | #145 | X15a0_X1aa | #165 | - | | -

**Comment by keflavich** [comment]
@eacmills could you make this a pull request modifying https://github.com/ACES-CMZ/reduction_ACES/blob/main/aces/data/tables/SB_naming.tsv ?

**Comment by eacmills** [comment]
ORPHANS (MOUS not included in tsv table): #35, #126, #254, #255, #259, #265, #266, #272, #315, #317, #322, #324, #325

Open issues not included: #15, #19, #34, #39, #42, #44 (all tagged as reobserved; should these be closed?) 

#13, #26, #36 have an MOUS in the tsv table but issues are tagged as wrong velo shift

**Comment by keflavich** [comment]
Need to integrate the remainder of Betsy's list into the file, as in https://github.com/ACES-CMZ/reduction_ACES/pull/330.

 * [ ] #35
 * [ ] #126
 * [ ] #254
 * [ ] #255
 * [ ] #259
 * [ ] #265
 * [ ] #266
 * [ ] #272
 * [ ] #315
 * [ ] #317
 * [ ] #322
 * [ ] #324
 * [ ] #325

**Comment by eacmills** [comment]
Not sure what to do with the last one (#35) since it was superseded by a re-observation (velocity shift) so presumably it is just an orphan observation we won't really use further

**Comment by keflavich** [comment]
I think we can call this resolved now and close it: `SB_naming.tsv` now contains this information.
