### ISSUE TITLE
Update on history and current status of SBs

### ISSUE THREAD

**Issue by snlongmore** [ACES-CMZ/reduction_ACES#82]
Ana Karla (Contact Scientist) has kindly provided the following slides outlining the history and current status of the SBs:
[ACES_SB_status.pdf](https://github.com/ACES-CMZ/reduction_ACES/files/8283394/ACES_SB_status.pdf)

**Comment by keflavich** [comment]
Imaging prioritization:

1. Brick (03,41)
2. Sgr A* (43)
3. Extended Sgr B2 (02, 40, 13, 9, 10, 37, 26, 44)
4. Negative Longitude (17, 42, 31, 33, 30, 36, 05, 20, 25)

**Comment by ashleythomasbarnes** [comment]
quick drawing - scribbles are the blocks we've now scheduled with priority

![Screenshot 2022-03-21 at 15 21 04](https://user-images.githubusercontent.com/30494539/159283190-df6e057e-f60c-43b6-89d8-62b0225fee0e.png)
